version: '3.9'

services:
  vuestore-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - app_node_modules:/app/node_modules
      - app_dotvuestore:/app/.nuxt
    command: [npm,"run", dev]

volumes:
  app_node_modules:
  app_dotvuestore: