version: '3.9'

services:
  vuestore-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules/
      - app_dotvuestore:/app/.nuxt
    command: [yarn,run, dev]

volumes:
  app_dotvuestore: